version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bytes
    versions:
    - 1.0.0
  - dependency-name: tokio
    versions:
    - 1.0.1
  - dependency-name: futures
    versions:
    - 0.3.6
  - dependency-name: sha2
    versions:
    - 0.9.2
  - dependency-name: nom
    versions:
    - 6.0.1
